// Comprehensive e-commerce shop categories
export const categories = [
  { value: "electronics", label: "Electronics" },
  { value: "fashion_clothing", label: "Fashion & Clothing" },
  { value: "home_garden", label: "Home & Garden" },
  { value: "health_beauty", label: "Health & Beauty" },
  { value: "sports_outdoors", label: "Sports & Outdoors" },
  { value: "books_media", label: "Books & Media" },
  { value: "toys_games", label: "Toys & Games" },
  { value: "automotive", label: "Automotive" },
  { value: "jewelry_accessories", label: "Jewelry & Accessories" },
  { value: "food_beverages", label: "Food & Beverages" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "baby_kids", label: "Baby & Kids" },
  { value: "office_supplies", label: "Office Supplies" },
  { value: "tools_hardware", label: "Tools & Hardware" },
  { value: "furniture", label: "Furniture" },
  { value: "appliances", label: "Appliances" },
  { value: "computers_tech", label: "Computers & Technology" },
  { value: "mobile_tablets", label: "Mobile & Tablets" },
  { value: "cameras_photo", label: "Cameras & Photography" },
  { value: "audio_video", label: "Audio & Video" },
  { value: "gaming", label: "Gaming" },
  { value: "smart_home", label: "Smart Home" },
  { value: "wearable_tech", label: "Wearable Technology" },
  { value: "mens_fashion", label: "Men's Fashion" },
  { value: "womens_fashion", label: "Women's Fashion" },
  { value: "shoes_footwear", label: "Shoes & Footwear" },
  { value: "bags_luggage", label: "Bags & Luggage" },
  { value: "watches", label: "Watches" },
  { value: "sunglasses_eyewear", label: "Sunglasses & Eyewear" },
  { value: "skincare", label: "Skincare" },
  { value: "makeup_cosmetics", label: "Makeup & Cosmetics" },
  { value: "hair_care", label: "Hair Care" },
  { value: "fragrances", label: "Fragrances" },
  { value: "personal_care", label: "Personal Care" },
  { value: "vitamins_supplements", label: "Vitamins & Supplements" },
  { value: "fitness_equipment", label: "Fitness Equipment" },
  { value: "outdoor_recreation", label: "Outdoor Recreation" },
  { value: "cycling", label: "Cycling" },
  { value: "water_sports", label: "Water Sports" },
  { value: "winter_sports", label: "Winter Sports" },
  { value: "team_sports", label: "Team Sports" },
  { value: "running_jogging", label: "Running & Jogging" },
  { value: "yoga_pilates", label: "Yoga & Pilates" },
  { value: "martial_arts", label: "Martial Arts" },
  { value: "fiction_books", label: "Fiction Books" },
  { value: "non_fiction", label: "Non-Fiction Books" },
  { value: "textbooks", label: "Textbooks" },
  { value: "ebooks", label: "E-books" },
  { value: "audiobooks", label: "Audiobooks" },
  { value: "magazines", label: "Magazines" },
  { value: "movies_tv", label: "Movies & TV" },
  { value: "music", label: "Music" },
  { value: "video_games", label: "Video Games" },
  { value: "action_figures", label: "Action Figures" },
  { value: "board_games", label: "Board Games" },
  { value: "puzzles", label: "Puzzles" },
  { value: "dolls_plushies", label: "Dolls & Plushies" },
  { value: "educational_toys", label: "Educational Toys" },
  { value: "outdoor_toys", label: "Outdoor Toys" },
  { value: "building_blocks", label: "Building Blocks" },
  { value: "remote_control", label: "Remote Control Toys" },
  { value: "car_parts", label: "Car Parts & Accessories" },
  { value: "motorcycle_parts", label: "Motorcycle Parts" },
  { value: "car_electronics", label: "Car Electronics" },
  { value: "tires_wheels", label: "Tires & Wheels" },
  { value: "car_care", label: "Car Care & Detailing" },
  { value: "fine_jewelry", label: "Fine Jewelry" },
  { value: "fashion_jewelry", label: "Fashion Jewelry" },
  { value: "precious_metals", label: "Precious Metals" },
  { value: "gemstones", label: "Gemstones" },
  { value: "handmade_jewelry", label: "Handmade Jewelry" },
  { value: "organic_food", label: "Organic Food" },
  { value: "gourmet_food", label: "Gourmet Food" },
  { value: "beverages", label: "Beverages" },
  { value: "snacks", label: "Snacks" },
  { value: "cooking_ingredients", label: "Cooking Ingredients" },
  { value: "dietary_supplements", label: "Dietary Supplements" },
  { value: "dog_supplies", label: "Dog Supplies" },
  { value: "cat_supplies", label: "Cat Supplies" },
  { value: "bird_supplies", label: "Bird Supplies" },
  { value: "fish_aquarium", label: "Fish & Aquarium" },
  { value: "small_pets", label: "Small Pet Supplies" },
  { value: "pet_food", label: "Pet Food" },
  { value: "pet_toys", label: "Pet Toys" },
  { value: "baby_clothing", label: "Baby Clothing" },
  { value: "baby_gear", label: "Baby Gear" },
  { value: "baby_feeding", label: "Baby Feeding" },
  { value: "baby_safety", label: "Baby Safety" },
  { value: "kids_clothing", label: "Kids Clothing" },
  { value: "kids_shoes", label: "Kids Shoes" },
  { value: "school_supplies", label: "School Supplies" },
  { value: "stationery", label: "Stationery" },
  { value: "office_furniture", label: "Office Furniture" },
  { value: "office_electronics", label: "Office Electronics" },
  { value: "printing_supplies", label: "Printing Supplies" },
  { value: "power_tools", label: "Power Tools" },
  { value: "hand_tools", label: "Hand Tools" },
  { value: "hardware", label: "Hardware" },
  { value: "electrical", label: "Electrical Supplies" },
  { value: "plumbing", label: "Plumbing Supplies" },
  { value: "paint_supplies", label: "Paint & Supplies" },
  { value: "safety_equipment", label: "Safety Equipment" },
  { value: "living_room", label: "Living Room Furniture" },
  { value: "bedroom", label: "Bedroom Furniture" },
  { value: "dining_room", label: "Dining Room Furniture" },
  { value: "office_furniture_cat", label: "Office Furniture" },
  { value: "outdoor_furniture", label: "Outdoor Furniture" },
  { value: "storage_organization", label: "Storage & Organization" },
  { value: "kitchen_appliances", label: "Kitchen Appliances" },
  { value: "laundry_appliances", label: "Laundry Appliances" },
  { value: "small_appliances", label: "Small Appliances" },
  { value: "heating_cooling", label: "Heating & Cooling" },
  { value: "vacuum_cleaners", label: "Vacuum Cleaners" },
  { value: "laptops", label: "Laptops" },
  { value: "desktops", label: "Desktop Computers" },
  { value: "computer_components", label: "Computer Components" },
  { value: "monitors", label: "Monitors" },
  { value: "keyboards_mice", label: "Keyboards & Mice" },
  { value: "printers_scanners", label: "Printers & Scanners" },
  { value: "networking", label: "Networking Equipment" },
  { value: "software", label: "Software" },
  { value: "smartphones", label: "Smartphones" },
  { value: "tablets", label: "Tablets" },
  { value: "phone_accessories", label: "Phone Accessories" },
  { value: "tablet_accessories", label: "Tablet Accessories" },
  { value: "phone_cases", label: "Phone Cases" },
  { value: "screen_protectors", label: "Screen Protectors" },
  { value: "dslr_cameras", label: "DSLR Cameras" },
  { value: "mirrorless_cameras", label: "Mirrorless Cameras" },
  { value: "point_shoot", label: "Point & Shoot Cameras" },
  { value: "action_cameras", label: "Action Cameras" },
  { value: "camera_lenses", label: "Camera Lenses" },
  { value: "camera_accessories", label: "Camera Accessories" },
  { value: "photo_printing", label: "Photo Printing" },
  { value: "headphones", label: "Headphones" },
  { value: "speakers", label: "Speakers" },
  { value: "sound_systems", label: "Sound Systems" },
  { value: "turntables", label: "Turntables" },
  { value: "musical_instruments", label: "Musical Instruments" },
  { value: "audio_equipment", label: "Audio Equipment" },
  { value: "tv_video", label: "TV & Video" },
  { value: "console_games", label: "Console Games" },
  { value: "pc_games", label: "PC Games" },
  { value: "gaming_consoles", label: "Gaming Consoles" },
  { value: "gaming_accessories", label: "Gaming Accessories" },
  { value: "gaming_chairs", label: "Gaming Chairs" },
  { value: "vr_equipment", label: "VR Equipment" },
  { value: "smart_speakers", label: "Smart Speakers" },
  { value: "smart_lighting", label: "Smart Lighting" },
  { value: "smart_security", label: "Smart Security" },
  { value: "smart_thermostats", label: "Smart Thermostats" },
  { value: "home_automation", label: "Home Automation" },
  { value: "smart_appliances", label: "Smart Appliances" },
  { value: "fitness_trackers", label: "Fitness Trackers" },
  { value: "smartwatches", label: "Smartwatches" },
  { value: "smart_glasses", label: "Smart Glasses" },
  { value: "wearable_accessories", label: "Wearable Accessories" },
  { value: "kitchen_dining", label: "Kitchen & Dining" },
  { value: "bedding_bath", label: "Bedding & Bath" },
  { value: "home_decor", label: "Home Decor" },
  { value: "lighting", label: "Lighting" },
  { value: "rugs_carpets", label: "Rugs & Carpets" },
  { value: "curtains_blinds", label: "Curtains & Blinds" },
  { value: "wall_art", label: "Wall Art" },
  { value: "candles_fragrance", label: "Candles & Home Fragrance" },
  { value: "gardening", label: "Gardening" },
  { value: "outdoor_living", label: "Outdoor Living" },
  { value: "grills_outdoor", label: "Grills & Outdoor Cooking" },
  { value: "pool_spa", label: "Pool & Spa" },
  { value: "patio_furniture", label: "Patio Furniture" },
  { value: "lawn_care", label: "Lawn Care" },
  { value: "arts_crafts", label: "Arts & Crafts" },
  { value: "sewing_fabric", label: "Sewing & Fabric" },
  { value: "scrapbooking", label: "Scrapbooking" },
  { value: "painting_drawing", label: "Painting & Drawing" },
  { value: "jewelry_making", label: "Jewelry Making" },
  { value: "woodworking", label: "Woodworking" },
  { value: "model_building", label: "Model Building" },
  { value: "collectibles", label: "Collectibles" },
  { value: "antiques", label: "Antiques" },
  { value: "coins_stamps", label: "Coins & Stamps" },
  { value: "trading_cards", label: "Trading Cards" },
  { value: "memorabilia", label: "Memorabilia" },
  { value: "vintage_items", label: "Vintage Items" },
  { value: "travel_luggage", label: "Travel & Luggage" },
  { value: "travel_accessories", label: "Travel Accessories" },
  { value: "camping_hiking", label: "Camping & Hiking" },
  { value: "travel_gear", label: "Travel Gear" },
  { value: "maps_guides", label: "Maps & Travel Guides" },
  { value: "industrial_supplies", label: "Industrial Supplies" },
  { value: "medical_supplies", label: "Medical Supplies" },
  { value: "laboratory", label: "Laboratory Equipment" },
  { value: "restaurant_supplies", label: "Restaurant Supplies" },
  { value: "cleaning_supplies", label: "Cleaning Supplies" },
  { value: "packaging_shipping", label: "Packaging & Shipping" },
  { value: "wholesale_bulk", label: "Wholesale & Bulk" },
  { value: "gift_cards", label: "Gift Cards" },
  { value: "digital_products", label: "Digital Products" },
  { value: "services", label: "Services" },
  { value: "subscriptions", label: "Subscriptions" },
  { value: "other", label: "Other" },
];
